### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: 

### ISSUE THREAD

**Issue by hjanjua** [VingtCinq/python-mailchimp#157]
Getting following error trying to get all members of the list.

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    client.lists.members.all('75765', get_all=True, fields="members.email_address,members.id")
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/entities/listmembers.py", line 94, in all
    return self._iterate(url=self._build_path(list_id, 'members'), **queryparams)
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/baseapi.py", line 59, in _iterate
    result = self._mc_client._get(url=url, offset=0, count=5000, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/mailchimpclient.py", line 28, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mailchimp3/mailchimpclient.py", line 139, in _get
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests-2.18.4-py2.7.egg/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://us17.api.mailchimp.com/3.0/lists/75765/members?count=5000&fields=members.email_address%2Cmembers.id%2Ctotal_items&offset=0

**Comment by charlesthk** [comment]
Hi @hjanjua, thanks for your feedback.

I have tried on an account of mine to reproduce the problem but everything was fine.

Here are my thoughts :
+ Do you still have this issue ?
+ It might be to an unavailability of mailchimp service at that specific time ?

**Comment by lamar-frankie** [comment]
@charlesthk I would like to contribute to this project. Are there any issues you would like me to work on?

**Comment by charlesthk** [comment]
Hi @lamar-frankie, thanks for offering your help. You are very welcome to contribute.

The #158 issue is an important one, your could work on it ? Maybe @stephenross is working on it too ?

Thanks.

**Comment by lamar-frankie** [comment]
@charlesthk Also, It looks like you're doing manual deployments. When I finish with this bug maybe we can discuss some continuous integration options. I'd be happy to help with that also.
